Develop
SyncLife-SHOBot/backend pull request #5
Opened 2024-11-14 16:16 UTC by LucasA21

Crud Inventory

2024-11-15 13:33 UTC, GiulianoPoeta99 requested changes
Hay muchas cositas para arreglar, me quedo esperando a las dudas jajajjaja

2024-11-15 13:33 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/infrastructure/persistence/repositories/sqlmodel_inventory_repository.py
> +    def find_all(self) -> List[Inventory]:
no discrimina si el item fue eliminado

2024-11-15 13:33 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/infrastructure/persistence/repositories/sqlmodel_inventory_repository.py
> +    def find_by_id(self, id: Uuid) -> Optional[Inventory]:
no discrimina si el item fue eliminado

2024-11-15 13:33 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/infrastructure/persistence/repositories/sqlmodel_inventory_repository.py
> +    def update(self, item: Inventory) -> bool:
Fijate en el user repository que esto lo cambie por un tema de validacion, hace lo mismo.

2024-11-15 13:33 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/infrastructure/persistence/repositories/sqlmodel_inventory_repository.py
> +    def delete(self, item: Inventory) -> bool:
Lo mismo que en update

2024-11-15 13:33 UTC, GiulianoPoeta99 commented on src/api/v1/user/domain/entities/user.py
Esto esta bien pero analizandolo me di cuenta que te falta un caso de uso. Vos hiciste el caso de uso de view inventory item, pero este atributo es para el caso de uso de view all que no lo hiciste porque no estaba en el diagrama.
Agregalo al diagrama y hacelo. Y con este atributo vas a tener que agregar en user una forma de hacer el lazy load de la lista. Capaz un get que pregunta si la lista esta vacia y si lo esta busca los datos o algo similar.

2024-11-15 13:33 UTC, GiulianoPoeta99 commented on src/api/v1/user/infrastructure/persistence/models/sqlmodel_user_model.py
Esto aclaramelo, modificaste aca para hacer la relacion 1 a n? se hace asi en sqlmodel?

2024-11-15 13:48 UTC, GiulianoPoeta99 commented
También cambiamos el título de la pr a uno con la convención de los commits porque después esto se vuelve uno. Y mejora un poco la descripción

2024-11-28 21:40 UTC, GiulianoPoeta99 requested changes
Acordate tambien de cambiar el titulo y la descriptcion de la pr respetando los estandares de conventional commits, porque despues el titulo queda como un commit y no quiero que quede "develop".

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on alembic/env.py
Supongo que lo cambiaste por tema de importaciones circulres o no?

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on alembic/versions/inventory_item/1aec6638c2df_inventory_item_create.py
esto no hace nada

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on alembic/versions/inventory_item/25f0fd2b753f_inventory_item_create.py
esto no hace nada

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on alembic/versions/inventory_item/458165d4765f_initial_migration.py
esto no hace nada

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on alembic/versions/inventory_item/abff64c4ac58_initial_migration.py
esto no hace nada

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on alembic/versions/user/581d6326c67e_merge_heads.py
esto no hace nada

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/create/create_item_use_case.py
agregale al nombre de la clase al final que es un caso de uso, asi "CreteItemUseCase"

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/create/create_item_use_case.py
> +        if not user:
En el caso de uso de view account de user hay un ejemplo de un validator que hice para evitar hacer el if de esta manera

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/delete/delete_item_use_case.py
Agregale al final del nombre UseCase

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/delete/delete_item_use_case.py
> +        deleted_item: Optional[Inventory]
creo que no hace falta definir las variables antes, no es un error pero probalo

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/update/update_item_use_case.py
Agregale el UseCase al nombre

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/update/update_item_use_case.py
> +        updated_item: Optional[Inventory]
lo mismo que en el anterior, no se si hace falta

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/view/view_item_use_case.py
Agregale UseCase al nombre

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/view_all/view_all_item_dto.py
Viendo este dto revisa que la mejor opcion es hacerlo un dataclass, fijate en user como estan.

Seguramente tengas que revisar todos los dtos.

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/application/view_all/view_item_all_use_case.py
Agregale UseCase al nombre

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/infrastructure/http/controllers/fastapi_inventory_controller.py
Fijate como esta el controller de user, quedo con el estandar viejo. No deberias tener que usar el with.

Ademas ya que estas estaba pensando que podes hacer que el exeption handler este en shared y que soporte los errores de usuario y de inventoryi ademas del de shared.

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/inventory/infrastructure/persistence/models/sqlmodel_inventory_model.py
aca es lo que estuvimos hablando, si el type checking te andaba bien dejalo. Y si no era el caso esta perfecto.

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/api/v1/user/infrastructure/http/services/in_memory_session_service.py
despues hay que aclarar en cuanto tiempo quedo.

2024-11-28 21:40 UTC, GiulianoPoeta99 commented on src/main.py
que hace el loggin? porque habria que ponerlo como una variable del .env

2024-11-28 21:47 UTC, LucasA21 commented on alembic/env.py
Si

2024-11-29 23:53 UTC, GiulianoPoeta99 approved these changes
Se ve todo bien, sacaste algunas cosas como el logger o el tiempo de la cookie, supongo que no hacian falta. APROBAO

2024-11-29 23:53 UTC, merged